### ISSUE TITLE
Run 2 Bluestack with 2 Gui

### ISSUE THREAD

**Issue by hatehackppl** [Jimm1432/Rush-Royale-Bot#8]
Isit possible to run 2 Gui? its more easy to play PVE with friends which using 2 bluestack running...

**Comment by Jimm1432** [comment]
It's possible but would be a pain.
If you really want to run multiple bots you will need to have separate folders for each bot and change the port_scan.py file so it connects to the right port. The fastest way would probably be run one bot/bluestacks then run the next bluestacks and change the port_scan.py file to connect directly instead of scanning for it.

I have no plans of making it multiple instance.
